name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: install zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.0
      - name: add repository
        run: opam repo add cross .
      - name: configure and install x86-64-linux-gnu cross
        run: opam install conf-ocaml-cross conf-zig-wrapper
        env:
          HOST_TRIPLE: x86_64-linux-gnu
          HOST_TARGET: x86_64-linux-gnu
          ZIG_PATH: zig
      - name: install compiler
        run: opam install ocaml-cross --verbose || cat /home/runner/work/opam-cross-generic/opam-cross-generic/_opam/.opam-switch/build/ocaml-cross.5.2.0/config.log

          
