name: Builds, tests & co

on:
  - pull_request:
      branches: [main]
  - push: 
      branches: [main]

permissions: read-all

jobs:
  aarch64-linux-gnu_5_2:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: install zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.0
      - name: add repository
        run: opam repo add cross .
      - name: configure and install x86-64-linux-gnu cross
        run: opam install conf-ocaml-cross conf-zig-wrapper
        env:
          HOST_TRIPLE: aarch64-linux-gnu
          HOST_TARGET: aarch64-linux-gnu
          ZIG_PATH: zig
      - name: install compiler
        run: opam install ocaml-cross --verbose 

          
  aarch64-linux-gnu_5_3:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: install zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0
      - name: add repository
        run: opam repo add cross .
      - name: configure and install x86-64-linux-gnu cross
        run: opam install conf-ocaml-cross conf-zig-wrapper
        env:
          HOST_TRIPLE: aarch64-linux-gnu
          HOST_TARGET: aarch64-linux-gnu
          ZIG_PATH: zig
      - name: install compiler
        run: opam install ocaml-cross --verbose 

          
